### ISSUE TITLE
v3.0.3+: Can't serve resume from local theme

### ISSUE THREAD

**Issue by paskal** [jsonresume/resume-cli#492]
## How to reproduce

```
# prepare
git clone https://github.com/paskal/resume.git
docker-compose build build
# run
docker-compose up serve
```

The expected result is resume.json served with jsonresume-theme-kendall-ksenia, the real one is following message in the log plus the try to fetch the theme from the server:

```
TypeError: renderHtml is not a function
    at /data/node_modules/resume-cli/build/builder.js:50:26
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
Could not run the render function from local theme.
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at denormalizeTheme (/data/node_modules/resume-cli/build/builder.js:14:46)
    at sendExportHTML (/data/node_modules/resume-cli/build/builder.js:20:30)
    at /data/node_modules/resume-cli/build/builder.js:58:7
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
<...>
Requesting theme from server...
```

I assume `renderHtml is not a function` is not something I am supposed to see while running the `serve` command, might be a bug.

Serve settings:
```yaml
version: '2'
services:

    serve:
        image: paskal/jsonresume
        working_dir: /data/node_modules/jsonresume-theme-kendall-ksenia
        command: serve --theme .
        volumes:
            - ./resume.json:/data/node_modules/jsonresume-theme-kendall-ksenia/resume.json:ro
        ports:
            - "4000:4000"
```
