### ISSUE TITLE
publications should have identifiers

### ISSUE THREAD

**Issue by tmaier** [jsonresume/resume-cli#9]
like [DOI](http://en.wikipedia.org/wiki/Digital_object_identifier), ISBN or another number.

``` yaml
name: string
publisher: string
releaseDate: string
website: string
identifiers:
  - type: doi
    identifier: string // e.g.10.1000/182
  - type: isbn
    identifier: string // e.g. 978-3-16-148410-0
```
